runtime: nodejs
env: flex
service: site
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10